# Generated by Django 3.2.13 on 2022-05-27 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(max_length=200)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.ciudad')),
            ],
        ),
    ]
